// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRdh_bcfkrbghsAs5P3Cdo_PmHt5q1B90',
    appId: '1:868919169855:web:e21c4e9a5f4f4fcec8398a',
    messagingSenderId: '868919169855',
    projectId: 'splitmoney-94bfe',
    authDomain: 'splitmoney-94bfe.firebaseapp.com',
    storageBucket: 'splitmoney-94bfe.appspot.com',
    measurementId: 'G-999RWW751S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDusIn-aoJVMrGOzDJ9cxLgqm7_6zp_tw4',
    appId: '1:868919169855:android:a91001d8f2f80578c8398a',
    messagingSenderId: '868919169855',
    projectId: 'splitmoney-94bfe',
    storageBucket: 'splitmoney-94bfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp20YzAEdWYQOMnAWERu3NY7ROg-fQh4I',
    appId: '1:868919169855:ios:b357bb1858455b92c8398a',
    messagingSenderId: '868919169855',
    projectId: 'splitmoney-94bfe',
    storageBucket: 'splitmoney-94bfe.appspot.com',
    iosClientId: '868919169855-q14jll7vofctlk6cilntbac7vjktv377.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitmoney',
  );
}
